import { Course, Category } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Web Development', icon: '💻', color: 'bg-blue-500' },
  { id: '2', name: 'Data Science', icon: '📊', color: 'bg-purple-500' },
  { id: '3', name: 'Design', icon: '🎨', color: 'bg-pink-500' },
  { id: '4', name: 'Business', icon: '💼', color: 'bg-green-500' },
  { id: '5', name: 'Marketing', icon: '📢', color: 'bg-orange-500' },
  { id: '6', name: 'Photography', icon: '📸', color: 'bg-red-500' },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'Complete Web Development Bootcamp',
    description: 'Master modern web development with React, Node.js, and MongoDB. Build real-world projects and land your dream job.',
    instructor: 'Sarah Johnson',
    price: 89,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    category: 'Web Development',
    rating: 4.8,
    students: 12500,
    lessons: [
      { id: '1', title: 'Introduction to Web Development', duration: '15:30', type: 'video' },
      { id: '2', title: 'HTML Fundamentals', duration: '45:20', type: 'video' },
      { id: '3', title: 'CSS Styling', duration: '60:15', type: 'video' },
      { id: '4', title: 'JavaScript Basics', duration: '90:00', type: 'video' },
      { id: '5', title: 'React Fundamentals', duration: '120:00', type: 'video' },
      { id: '6', title: 'Quiz: Web Basics', duration: '30:00', type: 'quiz' },
    ],
  },
  {
    id: '2',
    title: 'Data Science & Machine Learning',
    description: 'Learn data science from scratch. Work with Python, pandas, scikit-learn, and TensorFlow to build ML models.',
    instructor: 'Dr. Michael Chen',
    price: 129,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    category: 'Data Science',
    rating: 4.9,
    students: 8900,
    lessons: [
      { id: '1', title: 'Introduction to Data Science', duration: '20:00', type: 'video' },
      { id: '2', title: 'Python for Data Analysis', duration: '75:30', type: 'video' },
      { id: '3', title: 'Data Visualization', duration: '65:45', type: 'video' },
      { id: '4', title: 'Machine Learning Basics', duration: '110:20', type: 'video' },
      { id: '5', title: 'Project: Predictive Model', duration: '180:00', type: 'assignment' },
    ],
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass',
    description: 'Create stunning user interfaces and exceptional user experiences. Master Figma, design systems, and prototyping.',
    instructor: 'Emma Davis',
    price: 79,
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    category: 'Design',
    rating: 4.7,
    students: 6700,
    lessons: [
      { id: '1', title: 'Design Principles', duration: '30:00', type: 'video' },
      { id: '2', title: 'Figma Basics', duration: '45:00', type: 'video' },
      { id: '3', title: 'Creating Design Systems', duration: '90:00', type: 'video' },
      { id: '4', title: 'Prototyping & Interactions', duration: '60:00', type: 'video' },
      { id: '5', title: 'Portfolio Project', duration: '150:00', type: 'assignment' },
    ],
  },
  {
    id: '4',
    title: 'Business Strategy & Leadership',
    description: 'Learn strategic thinking, leadership skills, and how to build successful businesses from industry experts.',
    instructor: 'Robert Williams',
    price: 99,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    category: 'Business',
    rating: 4.6,
    students: 5200,
    lessons: [
      { id: '1', title: 'Strategic Planning', duration: '40:00', type: 'video' },
      { id: '2', title: 'Leadership Fundamentals', duration: '55:30', type: 'video' },
      { id: '3', title: 'Team Management', duration: '50:00', type: 'video' },
      { id: '4', title: 'Case Study Analysis', duration: '70:00', type: 'video' },
    ],
  },
  {
    id: '5',
    title: 'Digital Marketing Pro',
    description: 'Master SEO, social media marketing, content strategy, and paid advertising to grow your business online.',
    instructor: 'Lisa Anderson',
    price: 69,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    category: 'Marketing',
    rating: 4.5,
    students: 9800,
    lessons: [
      { id: '1', title: 'Marketing Fundamentals', duration: '25:00', type: 'video' },
      { id: '2', title: 'SEO Optimization', duration: '80:00', type: 'video' },
      { id: '3', title: 'Social Media Strategy', duration: '65:00', type: 'video' },
      { id: '4', title: 'Content Marketing', duration: '55:00', type: 'video' },
      { id: '5', title: 'Quiz: Marketing Concepts', duration: '20:00', type: 'quiz' },
    ],
  },
  {
    id: '6',
    title: 'Photography Essentials',
    description: 'Capture stunning photos with any camera. Learn composition, lighting, editing, and build a professional portfolio.',
    instructor: 'James Wilson',
    price: 59,
    image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800',
    category: 'Photography',
    rating: 4.8,
    students: 3400,
    lessons: [
      { id: '1', title: 'Camera Basics', duration: '35:00', type: 'video' },
      { id: '2', title: 'Composition Techniques', duration: '50:00', type: 'video' },
      { id: '3', title: 'Lighting Mastery', duration: '60:00', type: 'video' },
      { id: '4', title: 'Photo Editing with Lightroom', duration: '85:00', type: 'video' },
    ],
  },
];

